theme: jekyll-theme-cayman
title: Relation-Shape Convolutional Neural Network for Point Cloud Analysis
description: [Yongcheng Liu](https://yochengliu.github.io/), Bin Fan, Shiming Xiang, Chunhong Pan <br> CVPR 2019
show_downloads: true